### ISSUE TITLE
Themes model should be singular

### ISSUE THREAD

**Issue by renatopanda** [mrsequeira/GuardiansOfTheHackathon#6]
Ontem o @Freakmania começou a fazer testes automatizados e corrigiu isto, sugiro que ele faça merge cedo com essas alterações para evitar que o problema se espalhe por outros branches ou que alguém duplique esse trabalho.

https://github.com/mrsequeira/GuardiansOfTheHackathon/blob/12626a75a682a942a6bbf63e50cf4293ac606124/app/models/themes.rb#L1

**Comment by mrsequeira** [comment]
@Freakmania Dá commit e push da correção que fizeste!   #10

**Comment by mrsequeira** [comment]
Closed by @migsilva95 #10
